config/routes.rb
Portfolio::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  # devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'signup' }
  # get 'signup', to: 'users#new', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'  # NOTE: this 'get' should be a 'delete'
  devise_scope :user do
    # get "signup", :to => "devise/registrations#new"
    get "signout", :to => "devise/sessions#destroy"
    # get "signin", :to => "devise/sessions#new"
  end

  resources :posts do
    member do
      put 'publish'
    end
  end

  resources :projects

  root :to => 'home#index'

  get ':action' => 'static#:action'  # replace 'match' with 'get' for rails4
end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible :content, :title, :published

  validates :title, :content, presence: true
  validates :title, length: { in: 2..255 }
  validates :content, length: { in: 3..255 }


  belongs_to :author, class_name: "User"
  # # TODO: we added this on Mon, 10/21.  For a reminder of class vs instance methods.
  # # class method
  # def self.published
  #   where(published: true)
  # end

  # # TODO: we added this on Mon, 10/21.  For a reminder of class vs instance methods.
  # # instance method
  # def publish!
  #   self.published = true
  #   save!
  # end
end

app/models/project.rb
class Project < ActiveRecord::Base
  # attr_accessible :name, :technologies_used

  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login
  attr_accessor :login
  # attr_accessible :title, :body
  has_many :posts, foreign_key: "author_id"

  validates_presence_of :username, unless: :email?
  validates_uniqueness_of :username, :case_sensitive => false

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to request.headers["Referer"] || root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email, :password, :password_confirmation, :remember_me, :login)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user, notice: "Signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  after_filter :verify_policy_scoped, :only => :index

  # GET /posts
  # GET /posts.json
  def index
    @posts = policy_scope(Post)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
      format.js
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    # @post = Post.new(params[:post])
    @post = Post.new(params.require(:post).permit(:content, :title, :published))
    authorize @post

    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
      format.js
    end
  end

  def publish
    @post = Post.find(params[:id])
    authorize @post

    @post.update_attributes(published: !@post.published)

    redirect_to posts_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    # @project = Project.new(params[:project])
    @project = Project.new(params.require(:project).permit(:name, :technologies_used))
    if @project.save
      flash[:notice] = "Project was successfully created."
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end

    # respond_to do |format|
    #   if @project.update_attributes(params[:project])
    #     format.html { redirect_to @project, notice: 'Project was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @projet.errors, status: :unprocessable_entity }
    #   end
    # end

  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end

  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def construction
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # translate the rails flash levels to appropriate twitter bootstrap css classes
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- Nothing here anymore.  Don't worry about it.  I may transfer a
bunch from application.html later, when/if I decide what I want to
see on all pages vs just the landing page.  Keeping the 'yield' in
the application.html.erb as well.  -sprestage Nov 15, 2013. -->

<!-- Adding google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46268095-5', 'geekymamamare.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_blog.html.erb
    <!-- Blog -->
    <div id="blog" class="blog">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h2>Share my journey through technology</h2>
<!-- TODO: re-add this line when I'm ready to launch the GeekyMamaMare blog -->
<!--             <h2>Share my journeys through technology</h2> -->
            <hr>
            <br>

            <a target="_blank" href="http://techblog.susanprestage.com">
              <img class="img-project img-responsive" src="https://s3-us-west-2.amazonaws.com/sprestageportfolio/images_for_portfolio/RubyOnRails.png" width="150" height="225">
              <p class="lead">My technical blog</p>
            </a>
            <hr>
            <br>
            <br>

<!-- TODO: re-add this line when I'm ready to launch the GeekyMamaMare blog -->
<!--             <a target="_blank" href="http://www.GeekyMamaMare.com">
              <img class="img-portfolio img-responsive" src="https://s3-us-west-2.amazonaws.com/sprestageportfolio/images_for_portfolio/SusanProfilePhoto.jpg" width="150" height="225">
              <br>
              <p class="lead">The story of my journey back to passion in technology</p>
            </a>
 -->
          </div>
        </div>
      </div>
    </div>
    <!-- /Blog -->

app/views/layouts/_call_to_action_button.html.erb
    <!-- Call to Action -->
    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h3>Please review my resume for additional details</h3>
            <a href="resume" class="btn btn-lg btn-primary">Resume</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /Call to Action -->

app/views/layouts/_callout.html.erb
    <!-- Callout -->
    <div class="callout">
      <div class="vert-text">
        <h1>A Dramatic Text Area</h1>
      </div>
    </div>
    <!-- /Callout -->

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <ul class="list-inline">
              <li><a href="http://github.com/sprestage"><i class="icon-github icon-2x"></i></a></li>
              <li><a href="http://linkedin.com/in/susanprestage"><i class="icon-linkedin icon-2x"></i></a></li>
              <li><a href="http://twitter.com/SusanPrestage"><i class="icon-twitter icon-2x"></i></a></li>
            </ul>
            <hr>
            <p>Copyright &copy; 2013-2016 Susan Prestage</p>
            <br>
            <p>
            <style>
              ccattribution {font-size:10px;}
            </style>
            <ccattribution>
              Attributes for background image of Seattle used above:
              <br>
              By
              <a href="http://web.jeffery-hayes.com/uploads/1/6/0/7/16078190/3412129_orig.jpg" >
                Jeffery Hayes
              </a>
              [
              <a href="http://creativecommons.org/licenses/by-sa/3.0">
                CC-BY-SA-3.0
              </a>
              ],
              <a href="http://commons.wikimedia.org/wiki/File%3ASeattle_Center_as_night_falls.jpg">
                via Wikimedia Commons
              </a>
            </ccattribution>
          </div>
        </div>
      </div>
    </footer>
    <!-- /Footer -->

app/views/layouts/_header.html.erb
  <div class="section-colored text-center">

      <div class="container">
        <div class="row">
          <div class"col-lg-12">
            <div id="user_header">
              <div class="nav">
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, id: "flash_#{name}" %>
              <% end %>

            </div>
          </div><!-- /.col -->
        </div><!-- /.row  -->
      </div><!-- /.container -->
</div>

app/views/layouts/_projects.html.erb
    <!-- Project -->
    <div id ="project" class="project" name="project">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h2>Projects</h2>
            <hr>
            <br>
          </div> <!-- /col -->
        </div> <!-- /row -->

        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <div class="project-item">
              <a href="http://www.unofficialtrakehnerdatabase.com">
                <img class="img-project img-responsive" src="https://s3-us-west-2.amazonaws.com/unofficialtrakehnerdb/unofficial-trakehner-db-website-image.png">
              <h4>Unofficial Trakehner DB</h4>
            </a>
              <hr>
              <br>
            </div> <!-- /item -->
          </div> <!-- /col -->
        </div> <!-- /row -->

        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <div class="project-item">
              <a href="http://www.tabarahranchtrakehners.com">
                <img class="img-project img-responsive" src="https://s3-us-west-2.amazonaws.com/tabarahranchtrakehners/tabarah-ranch-trakehners-website-image.png">
                <h4>Tabarah Ranch Trakehners Website</h4>
              </a>
              <hr>
            </div> <!-- /item -->
          </div> <!-- /col -->
        </div> <!-- /row -->
      </div> <!-- /container -->
    </div> <!-- /id -->
    <!-- /Project -->

app/views/layouts/_public_speaking.html.erb
    <!-- Speaking -->
    <div id="speaking" class="speaking">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>Public Speaking</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="text-left">
            <div class="col-md-12">
              <p>Public speaking has long been a challenge for me.  My experiences in 2013 have convinced me of the importance of putting effort into this skill.  You will find here my ideas for talks, starting with short lightning talks which I plan to slowly grow into longer talks.</p>
              <p>You will find links to my Haiku Decks, hosted and created using the wonderful tools provided by the good folks at <a href="http://www.haikudeck.com">Haiku Deck</a>, particular thanks to Catherine Carr, for her intro talk on this product at the <a href="http://www.codechix.org/seattle">CodeChix</a> meetup in December of 2013.  I have everything positive to say about Haiku Deck and how easy they make putting together slides with awesome pictures for presentations.</p>
              <hr>
              <br>
            </div> <!-- /col -->
          </div> <!-- /text -->
        </div> <!-- /row -->
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <div class="speaking-item">
              <h4>Lightning Talk Ideas/Haiku Deck Links</h4>
              <hr>
              <a href = "http://www.haikudeck.com/imposter-syndrome-uncategorized-presentation-D2hQv0odIG">Impostor Syndrome</a>
            </div> <!-- /item -->
          </div> <!-- /col -->
        </div> <!-- /row -->
        <hr>

        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h4>Code Fellows Bootcamp Tech Talks</h4>
            <hr>
          </div>
        </div>
        <div class="row">
          <style>
            tiny {font-size:10px;}
          </style>

          <div class="col-md-3 col-md-offset-1 text-center">
            <div class="speaking-item">
              <a href="https://www.youtube.com/watch?v=CnSim-K7bfo">
                <h5>Intro to Cron</h5>
              </a>
              <tiny>(13+ minute talk)</tiny>
            </div> <!-- /item -->
          </div> <!-- /col -->
          <div class="col-md-4 text-center">
            <div class="speaking-item">
              <a href="https://www.youtube.com/watch?v=vutPSPlJ66o">
                <h5>Personal Introduction<br>&<br>TDD Tech Talk</h5>
              </a>
              <tiny>(1 minute)</tiny>
            </div> <!-- /item -->
          </div> <!-- /col -->
          <div class="col-md-2 text-center">
            <div class="speaking-item">
              <a href="https://www.youtube.com/watch?v=L5fJRkRnNis">
                <h5>Intro to VI</h5>
              </a>
              <tiny>(6+ minute talk)</tiny>
            </div> <!-- /item -->
          </div> <!-- /col -->
        </div> <!-- /row -->
      </div> <!-- /container -->
    </div> <!-- /speaking -->
    <!-- /Speaking -->

app/views/layouts/_side_menu.html.erb
    <!-- Side Menu -->
    <a id="menu-toggle" href="#" class="btn btn-primary btn-lg toggle"><i class="icon-reorder"></i></a>
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-primary btn-lg pull-right toggle"><i class="icon-remove"></i></a>
        <li class="sidebar-brand" style="color:#666666">Susan Prestage</li>
        <li><a href="#top">Home</a></li>
        <li><a href="#blog">Blogs</a></li>
        <li><a href="#skills">Skills</a></li>
        <li><a href="#project">Projects</a></li>
        <li><a href="#volunteer">Volunteering</a></li>
        <li><a href="#public_speaking">Public Speaking</a></li>
        <li><a href="resume">Resume</a></li>
        <li><a href="/static/construction">Under Construction</a></li>
      <% if !current_user %>
        <li><a href="/users/sign_in">Log In</a></li>
      <% end %>
      <% if current_user %>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% end %>
      </ul>
    </div>
    <!-- /Side Menu -->

app/views/layouts/_skills.html.erb
    <!-- Skills -->
    <div id="skills" class="skills" name="skills">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>My Skills</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-1 text-center">
            <div class="skill-item">
              <i class="skill-icon icon-cog"></i>
              <h4>Ruby on Rails</h4>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="skill-item">
              <i class="skill-icon icon-html5"></i>
              <h4>HTML5</h4>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="skill-item">
              <i class="skill-icon icon-css3"></i>
              <h4>CSS3</h4>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="skill-item">
<!--               <i class="skill-icon icon-embed-close"></i>
 -->              <i class="skill-icon icon-chevron-right"></i>
              <h4>JavaScript</h4>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="skill-item">
              <i class="skill-icon icon-plane"></i>
              <h4>jQuery</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Skills -->

app/views/layouts/_volunteering.html.erb
    <!-- Volunteer -->
    <div id="volunteer" class="volunteer">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>Volunteering</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5 col-md-offset-1 text-center">
            <div class="volunteer-item">
              <a href="http://railsbridge.org/about">
                <h4>RailsBridge TA</h4>
              </a>
              <p>RailsBridge works to make tech more diverse and welcoming by teaching programming, connecting human beings, and listening to people's needs. RailsBridge organizes and teaches free weekend workshops on Rails, Ruby, and HTML & CSS in cities all over the world, targeted at groups of people that are underrepresented in tech.
              </p>
            </div>
          </div>
          <div class="col-md-5 col-md-offset-1 text-center">
            <div class="volunteer-item">
              <a href="http://adadevelopersacademy.org/about">
                <h4>Ada Developers Academy TA</h4>
              </a>
              <p>Ada Developers Academy is a tuition-free programming school for women that teaches full-stack web development. Students learn Ruby, Rails, HTML/CSS, and JavaScript. Additionally, students learn how to work on agile development teams, use pair programming, scrum, and test-driven development in the classroom over 6 months.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Volunteer -->

app/views/layouts/_welcome.html.erb
    <!-- Full Page Image Header Area -->
    <div id="top" class="header">
      <div class="vert-text">
        <br><br><br><br>
        <h1>Susan Prestage</h1>
        <h3>Ruby on Rails Developer</h3>
        <br><br><br>
        <h3>Technology and continual learning are my passions.</h3>
        <h3>Are <em><strong>you</strong></em> ready to benefit?</h3>
        <br><br><br>
        <a href="#skills" class="btn btn-default btn-lg">Skills</a>
        <a href="#project" class="btn btn-default btn-lg">Projects</a>
        <a href="resume" class="btn btn-default btn-lg">Resume</a>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      </div>
    </div>
    <!-- /Full Page Image Header Area -->

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
      <tr id="<%= dom_id(post) %>">
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>

        <% if policy(post).update? %>
          <td><%= link_to 'Edit', edit_post_path(post), id: "edit_post_link", remote: true %></td>
        <% end %>

        <% if policy(post).destroy? %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
        <% end %>

        <% if policy(post).publish? %>
          <% if post.published? %>
            <td><%= link_to 'Unpublish', publish_post_path(post), {method: :put} %></td>
          <% else %>
            <td><%= link_to 'Publish', publish_post_path(post), {method: :put} %></td>
          <% end %>
        <% end %>
      </tr>

app/views/posts/create.js.erb
$('#new_post').remove();
$('#new_post_link').show();
$('#all_posts').append('<%= j render(@post) %>');

app/views/posts/destroy.js.erb
$('#post_<%= @post.id %>').remove();

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="section-colored text-center">
  <h1>Listing posts</h1>
</div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody class="posts" id="all_posts">
    <% @posts.each do |post| %>
      <%= render "post", post: post %>
    <% end %>
  </tbody>
</table>

<br />

<div class="section-colored text-center">
  <% if policy(Post).create? %>
    <%= link_to 'New Post', new_post_path, id: "new_post_link", remote: true %> <br><br>
  <% end %>

  <% if current_user %>
    Logged in as <%= current_user.email %> <br>
    <%= link_to "Sign Out", signout_path %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
$('#new_post_link').hide().after('<%= j render("form") %>');

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Author:</b>
  <%=  @post.author.email %>
</p>

<% if current_user %>
  Logged in as <%= current_user.email %>
<% end %>

<% if policy(@post).update? %>
  <%= link_to 'Edit', edit_post_path(@post) %>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
<%= link_to 'Cancel', :back %>

app/views/projects/index.html.erb
<div class="section-colored text-center">
  <h1 {text-align:center}>Listing projects</h1>
</div>

<% @projects.each do |project| %>
  <div class="project" id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.technologies_used %></p>
    <div class="nav">
      <%= link_to 'Show', project %> |
      <%= link_to 'Edit', edit_project_path(project) %> |
      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<br />
<div class="section-colored text-center">
<%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Technologies Used:</b>
  <%= @project.technologies_used %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>